# Generated by Django 5.1.4 on 2025-11-27 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('required_position', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('team_lead', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='media/cv')),
                ('selected_for_exam', models.BooleanField(default=False)),
                ('canceled_for_exam', models.BooleanField(default=False)),
                ('exam_attended', models.BooleanField(default=False)),
                ('obtained_marks', models.CharField(blank=True, default='0/0', max_length=10, null=True)),
                ('applicant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applicant', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='job.jobs')),
            ],
        ),
    ]
