# Generated by Django 5.1.4 on 2025-11-28 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KabupatenKota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Kode kabupaten/kota (4 digit)', max_length=4, unique=True)),
                ('nama', models.CharField(help_text='Nama kabupaten/kota', max_length=100)),
                ('jenis', models.CharField(choices=[('KABUPATEN', 'Kabupaten'), ('KOTA', 'Kota')], default='KABUPATEN', max_length=10)),
            ],
            options={
                'verbose_name': 'Kabupaten/Kota',
                'verbose_name_plural': 'Kabupaten/Kota',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Kode provinsi (2 digit)', max_length=2, unique=True)),
                ('nama', models.CharField(help_text='Nama provinsi', max_length=100)),
            ],
            options={
                'verbose_name': 'Provinsi',
                'verbose_name_plural': 'Provinsi',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Kode kecamatan (6 digit)', max_length=6, unique=True)),
                ('nama', models.CharField(help_text='Nama kecamatan', max_length=100)),
                ('kabupaten_kota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kecamatan', to='area.kabupatenkota')),
            ],
            options={
                'verbose_name': 'Kecamatan',
                'verbose_name_plural': 'Kecamatan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Desa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Kode desa/kelurahan (10 digit)', max_length=10, unique=True)),
                ('nama', models.CharField(help_text='Nama desa/kelurahan', max_length=100)),
                ('jenis', models.CharField(choices=[('DESA', 'Desa'), ('KELURAHAN', 'Kelurahan')], default='DESA', max_length=10)),
                ('kode_pos', models.CharField(blank=True, help_text='Kode pos', max_length=5, null=True)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desa', to='area.kecamatan')),
            ],
            options={
                'verbose_name': 'Desa/Kelurahan',
                'verbose_name_plural': 'Desa/Kelurahan',
                'ordering': ['nama'],
            },
        ),
        migrations.AddField(
            model_name='kabupatenkota',
            name='provinsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kabupaten_kota', to='area.provinsi'),
        ),
    ]
