# Generated by Django 5.2.9 on 2025-12-12 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Pembibitan', 'Pembibitan'), ('Penanaman', 'Penanaman'), ('Pemupukan', 'Pemupukan'), ('Perawatan', 'Perawatan'), ('Panen', 'Panen'), ('Pengolahan', 'Pengolahan'), ('Manajemen', 'Manajemen'), ('Pemasaran', 'Pemasaran'), ('Teknologi', 'Teknologi'), ('Lainnya', 'Lainnya')], max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('discussion', models.TextField(blank=True, help_text='Identifier dari user flutter untuk diskusi', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='core.tipcontributor')),
            ],
        ),
        migrations.CreateModel(
            name='TipDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.TextField(help_text='Identifier dari user flutter')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='tips.tip')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
