# Generated by Django 5.1.4 on 2025-11-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='consultant_name',
            field=models.CharField(blank=True, help_text='Nama konsultan/lembaga', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='name',
            field=models.CharField(blank=True, help_text='Nama kontributor', max_length=255, null=True),
        ),
    ]
