# Generated by Django 5.1.4 on 2025-11-29 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_tip_consultant_name_tip_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('consultant_name', models.CharField(blank=True, help_text='Nama konsultan/lembaga', max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tip',
            name='consultant_name',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='name',
        ),
        migrations.AddField(
            model_name='tip',
            name='discussion',
            field=models.TextField(blank=True, help_text='Identifier dari user flutter untuk diskusi', null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='tips.tipcontributor'),
        ),
    ]
