# Generated by Django 5.1.4 on 2025-11-29 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_tipcontributor_remove_tip_consultant_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.TextField(help_text='Identifier dari user flutter')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='tips.tip')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
