# Generated by Django 5.1.4 on 2025-12-04 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tipcontributor'),
        ('tips', '0005_tipcontributor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='core.tipcontributor'),
        ),
        migrations.DeleteModel(
            name='TipContributor',
        ),
    ]
