# Generated by Django 5.1.4 on 2025-12-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='category',
            field=models.CharField(choices=[('Pembibitan', 'Pembibitan'), ('Penanaman', 'Penanaman'), ('Pemupukan', 'Pemupukan'), ('Perawatan', 'Perawatan'), ('Panen', 'Panen'), ('Pengolahan', 'Pengolahan'), ('Manajemen', 'Manajemen'), ('Pemasaran', 'Pemasaran'), ('Teknologi', 'Teknologi'), ('Lainnya', 'Lainnya')], max_length=50),
        ),
    ]
