# Generated by Django 5.1.4 on 2026-04-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0007_alter_tip_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='tips/'),
        ),
    ]
