# Generated by Django 5.1.4 on 2026-04-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0008_alter_tip_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='category',
            field=models.CharField(choices=[('Pembibitan', 'Pembibitan'), ('Penanaman', 'Penanaman'), ('Pemupukan', 'Pemupukan'), ('Perawatan', 'Perawatan'), ('Panen', 'Panen'), ('Pengolahan', 'Pengolahan'), ('Manajemen', 'Manajemen'), ('Pemasaran', 'Pemasaran'), ('Teknologi', 'Teknologi'), ('Berita', 'Berita'), ('Lainnya', 'Lainnya')], max_length=50),
        ),
    ]
