# Generated by Django 5.2.9 on 2025-12-12 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=225)),
                ('address', models.CharField(blank=True, max_length=225)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('education', models.CharField(blank=True, max_length=225)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('work_experience_1', models.CharField(blank=True, max_length=225)),
                ('work_experience_2', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('value', models.JSONField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m2recruit.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m2recruit.test'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, choices=[('lulus', 'Lulus'), ('tidak_lulus', 'Tidak Lulus'), ('dipertimbangkan', 'Dipertimbangkan')], max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='m2recruit.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m2recruit.test')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='trait',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='m2recruit.trait'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m2recruit.question')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='m2recruit.answer')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswerBig5',
            fields=[
            ],
            options={
                'verbose_name': 'User Answer Big 5',
                'verbose_name_plural': 'User Answers Big 5',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('m2recruit.useranswer',),
        ),
        migrations.CreateModel(
            name='UserAnswerDope',
            fields=[
            ],
            options={
                'verbose_name': 'User Answer Dope',
                'verbose_name_plural': 'User Answers Dope',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('m2recruit.useranswer',),
        ),
        migrations.CreateModel(
            name='UserAnswerInterview',
            fields=[
            ],
            options={
                'verbose_name': 'User Answer Interview',
                'verbose_name_plural': 'User Answers Interview',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('m2recruit.useranswer',),
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_summary', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_test', to='m2recruit.testresult')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m2recruit.test')),
            ],
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='m2recruit.usertest'),
        ),
    ]
