# Generated by Django 5.2.3 on 2025-08-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='kk',
            field=models.FileField(blank=True, null=True, upload_to='document/kk'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ktp',
            field=models.FileField(blank=True, null=True, upload_to='document/ktp'),
        ),
        migrations.AddField(
            model_name='employee',
            name='npwp',
            field=models.FileField(blank=True, null=True, upload_to='document/npwp'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
