# Generated by Django 5.1.4 on 2025-11-28 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='desa',
            field=models.ForeignKey(blank=True, help_text='Desa/Kelurahan tempat tinggal karyawan', null=True, on_delete=django.db.models.deletion.SET_NULL, to='area.desa', verbose_name='Desa/Kelurahan'),
        ),
    ]
