# Generated by Django 5.2.3 on 2025-11-13 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_create_inital_group_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='default_allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tunjangan tetap bulanan', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='employee',
            name='pph21_status',
            field=models.CharField(blank=True, choices=[('TK/0', 'TK/0 - Tidak Kawin, tanpa tanggungan'), ('TK/1', 'TK/1 - Tidak Kawin, 1 tanggungan'), ('TK/2', 'TK/2 - Tidak Kawin, 2 tanggungan'), ('TK/3', 'TK/3 - Tidak Kawin, 3 tanggungan'), ('K/0', 'K/0 - Kawin, tanpa tanggungan'), ('K/1', 'K/1 - Kawin, 1 tanggungan'), ('K/2', 'K/2 - Kawin, 2 tanggungan'), ('K/3', 'K/3 - Kawin, 3 tanggungan'), ('HB/0', 'HB/0 - Istri bekerja, tanpa tanggungan (penghasilan digabung dengan suami)'), ('HB/1', 'HB/1 - Istri bekerja, 1 tanggungan'), ('HB/2', 'HB/2 - Istri bekerja, 2 tanggungan'), ('HB/3', 'HB/3 - Istri bekerja, 3 tanggungan')], default='', max_length=5, verbose_name='Status Pajak PPh 21'),
        ),
    ]
