# Generated by Django 5.1.4 on 2025-11-27 03:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee_basic_salary_employee_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borongan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pekerjaan', models.CharField(max_length=255)),
                ('satuan', models.CharField(max_length=100)),
                ('harga_borongan', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borongan', to='core.employee')),
            ],
            options={
                'verbose_name_plural': 'Borongan',
                'ordering': ['-created_at'],
            },
        ),
    ]
