# Generated by Django 5.1.4 on 2025-11-28 01:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Belum Mulai'), ('in_progress', 'Dalam Proses'), ('completed', 'Selesai'), ('revoked', 'Dicabut')], default='not_started', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='sertifikasi.certificationscheme')),
            ],
        ),
        migrations.CreateModel(
            name='CertificationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('in_progress', 'Dalam Proses'), ('done', 'Selesai')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sertifikasi.certificationprogress')),
            ],
        ),
    ]
