# Generated by Django 5.1.4 on 2025-12-01 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sertifikasi', '0002_certificationprogress_flutter_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificationtask',
            name='certification',
        ),
        migrations.CreateModel(
            name='CertificationSchemeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sertifikasi.certificationscheme')),
            ],
        ),
        migrations.DeleteModel(
            name='CertificationProgress',
        ),
        migrations.DeleteModel(
            name='CertificationTask',
        ),
    ]
