# Generated by Django 5.2.3 on 2025-11-13 14:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_employee_basic_salary_employee_birth_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BPJSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_jkk_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('emp_jkm_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('emp_jht_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('emp_jp_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('emp_jkn_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('com_jkk_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('com_jkm_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('com_jht_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('com_jp_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('com_jkn_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('working_days_per_month', models.PositiveSmallIntegerField(default=30, help_text='Hari kerja per bulan')),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=1.5, help_text='Rate lembur (mis. 1.5 untuk 150%)', max_digits=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('annual', 'Cuti Tahunan'), ('sick', 'Cuti Sakit'), ('maternity', 'Cuti Melahirkan'), ('other', 'Lainnya')], default='annual', max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Menunggu Approval'), ('approved_supervisor', 'Disetujui Supervisor'), ('approved_hr', 'Disetujui HR'), ('rejected', 'Ditolak')], default='pending', max_length=30)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_hr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_approvals', to=settings.AUTH_USER_MODEL)),
                ('approved_by_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_approvals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(help_text='Masukkan angka 1–12 untuk bulan', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveSmallIntegerField(help_text='Masukkan tahun antara 2000–2100', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('is_closed', models.BooleanField(default=False)),
                ('start_date', models.DateField(help_text='Tanggal awal periode penggajian')),
                ('end_date', models.DateField(help_text='Tanggal akhir periode penggajian')),
            ],
            options={
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tk_jkk_company', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tk_jkm_company', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tk_jht_company', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tk_jp_company', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jkn_company', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compensation6.payrollperiod')),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compensation6.payrollperiod')),
            ],
        ),
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compensation6.payrollperiod')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Hadir'), ('late', 'Terlambat'), ('absent', 'Tidak Hadir'), ('half_day', 'Setengah Hari')], default='present', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
