# Generated by Django 5.1.4 on 2025-11-27 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation6', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='borongan_harga',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Harga borongan untuk hari ini (opsional)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='attendance',
            name='borongan_pekerjaan',
            field=models.CharField(blank=True, help_text='Nama pekerjaan borongan (opsional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='borongan_satuan',
            field=models.CharField(blank=True, help_text='Satuan borongan (opsional)', max_length=100, null=True),
        ),
    ]
