# Generated by Django 5.1.4 on 2025-11-28 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation6', '0001_initial'),
        ('user_flutter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User yang membuat permintaan kerja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='flutter_user',
            field=models.ForeignKey(blank=True, help_text='Referensi user Flutter yang membuat permintaan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_requests', to='user_flutter.flutteruser'),
        ),
    ]
