# Generated by Django 5.1.4 on 2025-11-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compensation6', '0002_workrequest_created_by_workrequest_flutter_user'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workrequest',
            unique_together={('employee', 'start_date', 'end_date')},
        ),
    ]
