# Generated by Django 5.1.4 on 2025-11-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation6', '0002_add_borongan_to_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='borongan_dates',
            field=models.JSONField(blank=True, default=list, help_text='List of dates when borongan was recorded'),
        ),
    ]
