# Generated by Django 5.1.4 on 2025-11-27 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation6', '0003_add_borongan_dates_to_allowance'),
        ('core', '0006_borongan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='borongan_harga',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='borongan_pekerjaan',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='borongan_satuan',
        ),
        migrations.AddField(
            model_name='attendance',
            name='borongan',
            field=models.ForeignKey(blank=True, help_text='Pilih pekerjaan borongan (opsional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.borongan'),
        ),
    ]
