# Generated by Django 5.1.4 on 2025-11-27 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation6', '0004_replace_borongan_fields_with_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='realisasi',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Jumlah realisasi borongan (dalam satuan)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
