# Generated by Django 5.1.4 on 2025-11-27 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation6', '0005_add_realisasi_to_attendance'),
        ('core', '0006_borongan'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(help_text='Tanggal penugasan kerja')),
                ('due_date', models.DateField(help_text='Tanggal batas pengerjaan')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_requests', to='core.employee')),
            ],
            options={
                'ordering': ['-work_date', 'employee__name'],
                'unique_together': {('employee', 'work_date')},
            },
        ),
    ]
