# Generated by Django 5.1.4 on 2025-11-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation6', '0006_workrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workrequest',
            options={'ordering': ['-start_date', 'employee__name']},
        ),
        migrations.AlterUniqueTogether(
            name='workrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='end_date',
            field=models.DateField(blank=True, help_text='Tanggal akhir penugasan kerja', null=True),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='start_date',
            field=models.DateField(blank=True, help_text='Tanggal mulai penugasan kerja', null=True),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='due_date',
            field=models.DateField(blank=True, help_text='Tanggal batas pengerjaan', null=True),
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='work_date',
        ),
    ]
