# Generated by Django 5.1.4 on 2025-11-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation6', '0008_workrequest_date_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequest',
            name='end_date',
            field=models.DateField(blank=True, help_text='Tanggal akhir penugasan kerja', null=True),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='start_date',
            field=models.DateField(blank=True, help_text='Tanggal mulai penugasan kerja', null=True),
        ),
    ]
