# Generated by Django 5.2.9 on 2025-12-12 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetunjukKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Nama kategori', max_length=50, unique=True)),
                ('deskripsi', models.TextField(blank=True, help_text='Deskripsi kategori', null=True)),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Urutan tampilan')),
                ('aktif', models.BooleanField(default=True, help_text='Status aktif/non-aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategori Petunjuk',
                'verbose_name_plural': 'Kategori Petunjuk',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Petunjuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(help_text='Judul petunjuk', max_length=200)),
                ('konten', models.TextField(help_text='Isi petunjuk dalam format teks')),
                ('langkah_langkah', models.JSONField(blank=True, default=list, help_text='Array of steps untuk petunjuk berlangkah')),
                ('gambar', models.URLField(blank=True, help_text='URL gambar pendukung', null=True)),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Urutan tampilan')),
                ('aktif', models.BooleanField(default=True, help_text='Status aktif/non-aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(help_text='Kategori petunjuk', on_delete=django.db.models.deletion.CASCADE, related_name='petunjuk', to='petunjuk.petunjukkategori')),
            ],
            options={
                'verbose_name': 'Petunjuk',
                'verbose_name_plural': 'Petunjuk',
                'ordering': ['kategori', 'urutan', 'judul'],
            },
        ),
        migrations.CreateModel(
            name='PetunjukBaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_baca', models.DateTimeField(auto_now_add=True)),
                ('petunjuk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dibaca_oleh', to='petunjuk.petunjuk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petunjuk_dibaca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Petunjuk Dibaca',
                'verbose_name_plural': 'Petunjuk Dibaca',
                'unique_together': {('user', 'petunjuk')},
            },
        ),
    ]
