# Generated by Django 5.2.3 on 2025-10-14 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_order_paymentreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('current_score', models.PositiveSmallIntegerField(blank=True, help_text='Score 0-5', null=True)),
                ('desired_score', models.PositiveSmallIntegerField(blank=True, help_text='Score 0-5', null=True)),
                ('when_to_traine', models.DateField(blank=True, null=True)),
                ('jenis_pelatihan', models.CharField(blank=True, max_length=100)),
                ('done_at', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_competencies', to='learning5.competency')),
                ('detail_competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail_competencies', to='learning5.competency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.employee')),
            ],
            options={
                'unique_together': {('employee', 'competency', 'detail_competency')},
            },
        ),
    ]
