# Generated by Django 5.1.4 on 2025-12-06 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('pasar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacecomment',
            name='desa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_items', to='area.desa'),
        ),
        migrations.AddField(
            model_name='marketplacecomment',
            name='kabupaten_kota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_items', to='area.kabupatenkota'),
        ),
        migrations.AddField(
            model_name='marketplacecomment',
            name='kecamatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_items', to='area.kecamatan'),
        ),
        migrations.AddField(
            model_name='marketplacecomment',
            name='provinsi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_items', to='area.provinsi'),
        ),
    ]
