# Generated by Django 5.2.9 on 2025-12-12 04:08

import apps.modules.m9improvement.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcaiQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('dimension', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OcaiAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField()),
                ('expected', models.IntegerField()),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('period_year', models.IntegerField(default=apps.modules.m9improvement.models.current_year)),
                ('period_half', models.IntegerField(choices=[(1, 'H1'), (2, 'H2')], default=apps.modules.m9improvement.models.current_half)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocai_answer', to='m9improvement.ocaiquestion')),
            ],
            options={
                'unique_together': {('employee', 'question', 'period_year', 'period_half')},
            },
        ),
    ]
