# Generated by Django 5.2.3 on 2025-11-13 07:54

import apps.modules.m9improvement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee_basic_salary_employee_birth_date_and_more'),
        ('m9improvement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocaianswer',
            name='period_half',
            field=models.IntegerField(choices=[(1, 'H1'), (2, 'H2')], default=apps.modules.m9improvement.models.current_half),
        ),
        migrations.AddField(
            model_name='ocaianswer',
            name='period_year',
            field=models.IntegerField(default=apps.modules.m9improvement.models.current_year),
        ),
        migrations.AddField(
            model_name='ocaianswer',
            name='submit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ocaianswer',
            unique_together={('employee', 'question', 'period_year', 'period_half')},
        ),
    ]
