# Generated by Django 5.2.3 on 2025-11-09 11:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_order_paymentreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPICycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('period', models.CharField(choices=[('weekly', 'Mingguan'), ('monthly', 'Bulanan'), ('quarterly', 'Kuartalan'), ('semiannual', 'Semesteran'), ('annual', 'Tahunan')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_cycles', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='Weightage of the KPI in percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpis', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_kpis', to='core.employee')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kinerja4.kpicycle')),
            ],
        ),
        migrations.CreateModel(
            name='KPIPeriodTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('label', models.CharField(max_length=50)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_targets', to='kinerja4.kpi')),
            ],
            options={
                'unique_together': {('kpi', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='KPIEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Notes by employee')),
                ('notes_supervisor', models.TextField(blank=True, help_text='Notes by supervisor')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_evaluations', to=settings.AUTH_USER_MODEL)),
                ('period_target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='kinerja4.kpiperiodtarget')),
            ],
            options={
                'ordering': ['-evaluated_at'],
            },
        ),
    ]
