# Generated by Django 5.2.3 on 2025-11-05 16:14

from django.db import migrations


def create_kinerja4_permission(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    owner_group = Group.objects.get(name="Owner")
    content_type, _ = ContentType.objects.get_or_create(
        app_label="kinerja4", model="kpiperiodtarget"
    )

    perms = [
        ("add_kpiperiodtarget", "Can add kpi period target"),
        ("change_kpiperiodtarget", "Can change kpi period target"),
        ("delete_kpiperiodtarget", "Can delete kpi period target"),
        ("view_kpiperiodtarget", "Can view kpi period target"),
    ]

    for codename, name in perms:
        perm, _ = Permission.objects.get_or_create(
            codename=codename,
            content_type=content_type,
            defaults={"name": name},
        )
        if not owner_group.permissions.filter(pk=perm.pk).exists():
            owner_group.permissions.add(perm)


def remove_kinerja4_permission(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    owner_group = Group.objects.get(name="Owner")
    perms = [
        "add_kpiperiodtarget",
        "change_kpiperiodtarget",
        "delete_kpiperiodtarget",
        "view_kpiperiodtarget",
    ]

    for codename in perms:
        try:
            permission = Permission.objects.get(codename=codename)
            owner_group.permissions.remove(permission)
        except Permission.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("kinerja4", "0001_initial"),
        ("core", "0004_create_inital_group_permission"),
    ]

    operations = [
        migrations.RunPython(create_kinerja4_permission, remove_kinerja4_permission),
    ]
