# Generated by Django 5.1.4 on 2025-12-03 05:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_consultant'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCRRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='Format: YYYY-MM (e.g., 2025-10)', verbose_name='Period')),
                ('total_income', models.BigIntegerField(help_text='Total income (in IDR, without decimals)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Income')),
                ('total_labor_cost', models.BigIntegerField(help_text='Total labor cost (in IDR, without decimals)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Labor Cost')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lcr_records', to='core.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'LCR Record',
                'verbose_name_plural': 'LCR Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
