# Generated by Django 5.1.4 on 2025-11-29 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
        ('user_flutter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='user_flutter.flutteruser'),
        ),
        migrations.AlterField(
            model_name='consultationanswer',
            name='consultant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_flutter.flutteruser'),
        ),
    ]
