# Generated by Django 5.1.4 on 2025-11-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_alter_consultation_farmer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationanswer',
            name='consultant',
        ),
        migrations.AddField(
            model_name='consultationanswer',
            name='consultant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consultationanswer',
            name='institution_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
