# Generated by Django 5.1.4 on 2025-12-01 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_remove_consultationanswer_consultant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationanswer',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='consultation.consultation'),
        ),
    ]
