# Generated by Django 5.1.4 on 2025-12-01 06:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_consultationanswer_consultant_and_more'),
        ('user_flutter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='category',
            field=models.CharField(blank=True, help_text='Kategori pertanyaan untuk matching konsultan', max_length=100),
        ),
        migrations.AddField(
            model_name='consultation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='question',
            field=models.TextField(help_text='Pertanyaan dari petani'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('answered', 'Answered'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True, help_text='Bio/deskripsi singkat konsultan')),
                ('expertise_areas', models.JSONField(blank=True, default=list, help_text="List keahlian, misal: ['pertanian organik', 'hama tanaman', 'pupuk']")),
                ('specialization', models.CharField(blank=True, help_text='Spesialisasi utama', max_length=100)),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Pengalaman dalam tahun')),
                ('education', models.CharField(blank=True, help_text='Pendidikan terakhir', max_length=255)),
                ('certifications', models.JSONField(blank=True, default=list, help_text='List sertifikat/kualifikasi')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Rating rata-rata (0-5)', max_digits=3)),
                ('total_consultations', models.PositiveIntegerField(default=0, help_text='Total konsultasi yang pernah ditangani')),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_profile', to='user_flutter.flutteruser')),
            ],
            options={
                'ordering': ['-rating', '-total_consultations', 'name'],
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='assigned_consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_consultations', to='consultation.consultant'),
        ),
        migrations.CreateModel(
            name='ConsultationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('question', 'Pertanyaan'), ('answer', 'Jawaban'), ('follow_up', 'Tindak Lanjut'), ('info', 'Informasi')], default='question', max_length=20)),
                ('content', models.TextField(help_text='Isi pesan')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultant_messages', to='consultation.consultant')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='consultation.consultation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_messages', to='user_flutter.flutteruser')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
