# Generated by Django 5.1.4 on 2025-12-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_consultation_category_consultation_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='question',
            field=models.TextField(blank=True, help_text='Pertanyaan dari petani', null=True),
        ),
    ]
