# Generated by Django 5.1.4 on 2025-12-01 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_alter_consultation_question'),
        ('user_flutter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultant',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='education',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='expertise_areas',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='total_consultations',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='user',
        ),
        migrations.AlterField(
            model_name='consultant',
            name='bio',
            field=models.TextField(blank=True, help_text='Bio/deskripsi singkat konsultan', null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='institution_name',
            field=models.CharField(blank=True, help_text='Nama lembaga/institusi', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmessage',
            name='content',
            field=models.TextField(blank=True, help_text='Isi pesan', null=True),
        ),
        migrations.AlterField(
            model_name='consultationmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_messages', to='user_flutter.flutteruser'),
        ),
        migrations.CreateModel(
            name='ConsultationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Gambar untuk konsultasi', upload_to='consultation_images/')),
                ('caption', models.CharField(blank=True, help_text='Keterangan gambar', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant_uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to='consultation.consultant')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='consultation.consultation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='consultation.consultationmessage')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_consultation_images', to='user_flutter.flutteruser')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
