# Generated by Django 5.1.4 on 2025-12-02 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_alter_consultant_options_and_more'),
        ('user_flutter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationimage',
            name='consultant_uploader',
        ),
        migrations.RemoveField(
            model_name='consultationimage',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='consultationimage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='consultationimage',
            name='uploaded_by',
        ),
        migrations.AlterModelOptions(
            name='consultant',
            options={},
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='assigned_consultant',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='question',
        ),
        migrations.RemoveField(
            model_name='consultationmessage',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='consultationmessage',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='consultationmessage',
            name='sender',
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='consultation.consultant'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consultationmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='consultation_messages/'),
        ),
        migrations.AddField(
            model_name='consultationmessage',
            name='sender_consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages_consultant', to='consultation.consultant'),
        ),
        migrations.AddField(
            model_name='consultationmessage',
            name='sender_farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='user_flutter.flutteruser'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='institution_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='user_flutter.flutteruser'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmessage',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='consultation.consultation'),
        ),
        migrations.AlterField(
            model_name='consultationmessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultationmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='ConsultationAnswer',
        ),
        migrations.DeleteModel(
            name='ConsultationImage',
        ),
    ]
