# Generated by Django 5.1.4 on 2025-12-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0009_remove_consultationimage_consultant_uploader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='consultant_profiles/'),
        ),
    ]
