# Generated by Django 5.1.4 on 2025-12-02 09:04

import django.db.models.deletion
from django.db import migrations, models


def clear_consultant_refs(apps, schema_editor):
    Consultation = apps.get_model('consultation', 'Consultation')
    ConsultationMessage = apps.get_model('consultation', 'ConsultationMessage')
    Consultation.objects.filter(consultant__isnull=False).update(consultant=None)
    ConsultationMessage.objects.filter(sender_consultant__isnull=False).update(sender_consultant=None)


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0011_consultant_user_alter_consultation_farmer_and_more'),
        ('core', '0003_consultant'),
    ]

    operations = [
        migrations.RunPython(clear_consultant_refs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='consultation',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='core.consultant'),
        ),
        migrations.AlterField(
            model_name='consultationmessage',
            name='sender_consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_consultant_messages', to='core.consultant'),
        ),
        migrations.DeleteModel(
            name='Consultant',
        ),
    ]
